name = "deja-shared"
main = "src/shared-worker.ts"
compatibility_date = "2026-04-26"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "bfcb6ac5b3ceaf42a09607f6f7925823"

[[durable_objects.bindings]]
name = "SHARED_AUTHORITY"
class_name = "SharedAuthorityDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SharedAuthorityDO"]

[[routes]]
pattern = "deja-shared.coey.dev"
custom_domain = true
